server.port=8081
rest.base.url=http://localhost:8080
rest.user.name=admin
rest.user.password=admin

spring.jackson.serialization.write-dates-as-timestamps=false

spring.data.web.pageable.default-page-size=5
